// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere_rss_plugin/test/provider/rss_catalog_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readwhere_rss/src/client/rss_client.dart' as _i4;
import 'package:readwhere_rss/src/entities/rss_feed.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRssFeed_1 extends _i1.SmartFake implements _i2.RssFeed {
  _FakeRssFeed_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_2 extends _i1.SmartFake implements _i3.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RssClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRssClient extends _i1.Mock implements _i4.RssClient {
  MockRssClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.RssFeed> fetchFeed(
    String? url, {
    String? username,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchFeed,
              [url],
              {#username: username, #password: password},
            ),
            returnValue: _i6.Future<_i2.RssFeed>.value(
              _FakeRssFeed_1(
                this,
                Invocation.method(
                  #fetchFeed,
                  [url],
                  {#username: username, #password: password},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.RssFeed>);

  @override
  _i6.Future<_i2.RssFeed> validateFeed(
    String? url, {
    String? username,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateFeed,
              [url],
              {#username: username, #password: password},
            ),
            returnValue: _i6.Future<_i2.RssFeed>.value(
              _FakeRssFeed_1(
                this,
                Invocation.method(
                  #validateFeed,
                  [url],
                  {#username: username, #password: password},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.RssFeed>);

  @override
  _i6.Future<bool> isValidFeed(
    String? url, {
    String? username,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #isValidFeed,
              [url],
              {#username: username, #password: password},
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.File> downloadEnclosure(
    String? url,
    String? targetPath, {
    void Function(double)? onProgress,
    String? username,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadEnclosure,
              [url, targetPath],
              {
                #onProgress: onProgress,
                #username: username,
                #password: password,
              },
            ),
            returnValue: _i6.Future<_i3.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(
                  #downloadEnclosure,
                  [url, targetPath],
                  {
                    #onProgress: onProgress,
                    #username: username,
                    #password: password,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.File>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
