// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:readwhere/data/database/database_helper.dart' as _i12;
import 'package:readwhere/data/services/book_import_service.dart' as _i14;
import 'package:readwhere/domain/entities/book.dart' as _i2;
import 'package:readwhere/domain/entities/bookmark.dart' as _i3;
import 'package:readwhere/domain/entities/import_result.dart' as _i6;
import 'package:readwhere/domain/entities/reading_progress.dart' as _i4;
import 'package:readwhere/domain/repositories/book_repository.dart' as _i9;
import 'package:readwhere/domain/repositories/bookmark_repository.dart' as _i10;
import 'package:readwhere/domain/repositories/reading_progress_repository.dart'
    as _i11;
import 'package:readwhere_plugin/readwhere_plugin.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBook_0 extends _i1.SmartFake implements _i2.Book {
  _FakeBook_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookmark_1 extends _i1.SmartFake implements _i3.Bookmark {
  _FakeBookmark_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReadingProgress_2 extends _i1.SmartFake
    implements _i4.ReadingProgress {
  _FakeReadingProgress_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_3 extends _i1.SmartFake implements _i5.Database {
  _FakeDatabase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImportResult_4 extends _i1.SmartFake implements _i6.ImportResult {
  _FakeImportResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookMetadata_5 extends _i1.SmartFake implements _i7.BookMetadata {
  _FakeBookMetadata_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReaderController_6 extends _i1.SmartFake
    implements _i7.ReaderController {
  _FakeReaderController_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_7<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCursor_8 extends _i1.SmartFake implements _i5.QueryCursor {
  _FakeQueryCursor_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_9 extends _i1.SmartFake implements _i5.Batch {
  _FakeBatch_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i9.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.Book>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i8.Future<List<_i2.Book>>.value(<_i2.Book>[]),
          )
          as _i8.Future<List<_i2.Book>>);

  @override
  _i8.Future<_i2.Book?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i8.Future<_i2.Book?>.value(),
          )
          as _i8.Future<_i2.Book?>);

  @override
  _i8.Future<_i2.Book> insert(_i2.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [book]),
            returnValue: _i8.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#insert, [book])),
            ),
          )
          as _i8.Future<_i2.Book>);

  @override
  _i8.Future<_i2.Book> update(_i2.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#update, [book]),
            returnValue: _i8.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#update, [book])),
            ),
          )
          as _i8.Future<_i2.Book>);

  @override
  _i8.Future<bool> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i2.Book>> getRecent({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecent, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i2.Book>>.value(<_i2.Book>[]),
          )
          as _i8.Future<List<_i2.Book>>);

  @override
  _i8.Future<List<_i2.Book>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i8.Future<List<_i2.Book>>.value(<_i2.Book>[]),
          )
          as _i8.Future<List<_i2.Book>>);

  @override
  _i8.Future<List<_i2.Book>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i8.Future<List<_i2.Book>>.value(<_i2.Book>[]),
          )
          as _i8.Future<List<_i2.Book>>);

  @override
  _i8.Future<void> updateLastOpened(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastOpened, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.Book> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i8.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#toggleFavorite, [id])),
            ),
          )
          as _i8.Future<_i2.Book>);
}

/// A class which mocks [BookmarkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkRepository extends _i1.Mock
    implements _i10.BookmarkRepository {
  MockBookmarkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.Bookmark>> getBookmarksForBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarksForBook, [bookId]),
            returnValue: _i8.Future<List<_i3.Bookmark>>.value(<_i3.Bookmark>[]),
          )
          as _i8.Future<List<_i3.Bookmark>>);

  @override
  _i8.Future<_i3.Bookmark> addBookmark(_i3.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [bookmark]),
            returnValue: _i8.Future<_i3.Bookmark>.value(
              _FakeBookmark_1(
                this,
                Invocation.method(#addBookmark, [bookmark]),
              ),
            ),
          )
          as _i8.Future<_i3.Bookmark>);

  @override
  _i8.Future<bool> deleteBookmark(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.Bookmark> updateBookmark(_i3.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#updateBookmark, [bookmark]),
            returnValue: _i8.Future<_i3.Bookmark>.value(
              _FakeBookmark_1(
                this,
                Invocation.method(#updateBookmark, [bookmark]),
              ),
            ),
          )
          as _i8.Future<_i3.Bookmark>);
}

/// A class which mocks [ReadingProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingProgressRepository extends _i1.Mock
    implements _i11.ReadingProgressRepository {
  MockReadingProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.ReadingProgress?> getProgressForBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressForBook, [bookId]),
            returnValue: _i8.Future<_i4.ReadingProgress?>.value(),
          )
          as _i8.Future<_i4.ReadingProgress?>);

  @override
  _i8.Future<_i4.ReadingProgress> saveProgress(_i4.ReadingProgress? progress) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [progress]),
            returnValue: _i8.Future<_i4.ReadingProgress>.value(
              _FakeReadingProgress_2(
                this,
                Invocation.method(#saveProgress, [progress]),
              ),
            ),
          )
          as _i8.Future<_i4.ReadingProgress>);

  @override
  _i8.Future<bool> deleteProgressForBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgressForBook, [bookId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i12.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i5.Database>.value(
              _FakeDatabase_3(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i5.Database>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDatabase, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<int> rawExecute(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawExecute, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<String> getDatabasePath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, []),
            returnValue: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePath, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [BookImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookImportService extends _i1.Mock implements _i14.BookImportService {
  MockBookImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.ImportResult> importEpubWithValidation(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importEpubWithValidation, [filePath]),
            returnValue: _i8.Future<_i6.ImportResult>.value(
              _FakeImportResult_4(
                this,
                Invocation.method(#importEpubWithValidation, [filePath]),
              ),
            ),
          )
          as _i8.Future<_i6.ImportResult>);

  @override
  _i8.Future<_i2.Book> importEpub(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importEpub, [filePath]),
            returnValue: _i8.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#importEpub, [filePath])),
            ),
          )
          as _i8.Future<_i2.Book>);

  @override
  _i8.Future<_i2.Book> importBook(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importBook, [filePath]),
            returnValue: _i8.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#importBook, [filePath])),
            ),
          )
          as _i8.Future<_i2.Book>);

  @override
  _i8.Future<void> deleteCover(String? coverPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCover, [coverPath]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> extractCover(_i2.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#extractCover, [book]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);
}

/// A class which mocks [ReaderPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockReaderPlugin extends _i1.Mock implements _i7.ReaderPlugin {
  MockReaderPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  List<String> get supportedExtensions =>
      (super.noSuchMethod(
            Invocation.getter(#supportedExtensions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get supportedMimeTypes =>
      (super.noSuchMethod(
            Invocation.getter(#supportedMimeTypes),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<bool> canHandle(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#canHandle, [filePath]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i7.BookMetadata> parseMetadata(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#parseMetadata, [filePath]),
            returnValue: _i8.Future<_i7.BookMetadata>.value(
              _FakeBookMetadata_5(
                this,
                Invocation.method(#parseMetadata, [filePath]),
              ),
            ),
          )
          as _i8.Future<_i7.BookMetadata>);

  @override
  _i8.Future<_i7.ReaderController> openBook(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#openBook, [filePath]),
            returnValue: _i8.Future<_i7.ReaderController>.value(
              _FakeReaderController_6(
                this,
                Invocation.method(#openBook, [filePath]),
              ),
            ),
          )
          as _i8.Future<_i7.ReaderController>);

  @override
  _i8.Future<_i15.Uint8List?> extractCover(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#extractCover, [filePath]),
            returnValue: _i8.Future<_i15.Uint8List?>.value(),
          )
          as _i8.Future<_i15.Uint8List?>);
}

/// A class which mocks [ReaderController].
///
/// See the documentation for Mockito's code generation for more information.
class MockReaderController extends _i1.Mock implements _i7.ReaderController {
  MockReaderController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get bookId =>
      (super.noSuchMethod(
            Invocation.getter(#bookId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#bookId),
            ),
          )
          as String);

  @override
  List<_i7.TocEntry> get tableOfContents =>
      (super.noSuchMethod(
            Invocation.getter(#tableOfContents),
            returnValue: <_i7.TocEntry>[],
          )
          as List<_i7.TocEntry>);

  @override
  int get totalChapters =>
      (super.noSuchMethod(Invocation.getter(#totalChapters), returnValue: 0)
          as int);

  @override
  int get currentChapterIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentChapterIndex),
            returnValue: 0,
          )
          as int);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  _i8.Stream<_i7.ReaderContent> get contentStream =>
      (super.noSuchMethod(
            Invocation.getter(#contentStream),
            returnValue: _i8.Stream<_i7.ReaderContent>.empty(),
          )
          as _i8.Stream<_i7.ReaderContent>);

  @override
  bool get isFixedLayout =>
      (super.noSuchMethod(Invocation.getter(#isFixedLayout), returnValue: false)
          as bool);

  @override
  _i8.Future<void> goToChapter(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#goToChapter, [index]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> goToLocation(String? cfi) =>
      (super.noSuchMethod(
            Invocation.method(#goToLocation, [cfi]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> nextChapter() =>
      (super.noSuchMethod(
            Invocation.method(#nextChapter, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> previousChapter() =>
      (super.noSuchMethod(
            Invocation.method(#previousChapter, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.SearchResult>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i8.Future<List<_i7.SearchResult>>.value(
              <_i7.SearchResult>[],
            ),
          )
          as _i8.Future<List<_i7.SearchResult>>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i5.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  _i5.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_3(this, Invocation.getter(#database)),
          )
          as _i5.Database);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> transaction<T>(
    _i8.Future<T> Function(_i5.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action], {#exclusive: exclusive}),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> readTransaction<T>(
    _i8.Future<T> Function(_i5.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readTransaction, [action]),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> devInvokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeMethod, [method, arguments]),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawInsert, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i5.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [table, values],
              {
                #nullColumnHack: nullColumnHack,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i8.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i8.Future<List<Map<String, Object?>>>);

  @override
  _i8.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i8.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i8.Future<List<Map<String, Object?>>>);

  @override
  _i8.Future<_i5.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
            returnValue: _i8.Future<_i5.QueryCursor>.value(
              _FakeQueryCursor_8(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.QueryCursor>);

  @override
  _i8.Future<_i5.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
            returnValue: _i8.Future<_i5.QueryCursor>.value(
              _FakeQueryCursor_8(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i5.QueryCursor>);

  @override
  _i8.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i5.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, values],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i5.Batch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeBatch_9(this, Invocation.method(#batch, [])),
          )
          as _i5.Batch);
}
