// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/presentation/screens/catalogs/widgets/synology_folder_picker_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readwhere_synology/src/api/models/list_result.dart' as _i3;
import 'package:readwhere_synology/src/api/models/search_result.dart' as _i6;
import 'package:readwhere_synology/src/api/models/synology_file.dart' as _i4;
import 'package:readwhere_synology/src/api/synology_client.dart' as _i7;
import 'package:readwhere_synology/src/auth/synology_session.dart' as _i2;
import 'package:readwhere_synology/src/storage/session_storage.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSynologySession_0 extends _i1.SmartFake
    implements _i2.SynologySession {
  _FakeSynologySession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResult_1 extends _i1.SmartFake implements _i3.ListResult {
  _FakeListResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSynologyFile_2 extends _i1.SmartFake implements _i4.SynologyFile {
  _FakeSynologyFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_3 extends _i1.SmartFake implements _i5.File {
  _FakeFile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchResult_4 extends _i1.SmartFake implements _i6.SearchResult {
  _FakeSearchResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SynologyClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSynologyClient extends _i1.Mock implements _i7.SynologyClient {
  MockSynologyClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SynologySession> authenticate({
    required String? catalogId,
    required String? serverUrl,
    required String? account,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #catalogId: catalogId,
              #serverUrl: serverUrl,
              #account: account,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.SynologySession>.value(
              _FakeSynologySession_0(
                this,
                Invocation.method(#authenticate, [], {
                  #catalogId: catalogId,
                  #serverUrl: serverUrl,
                  #account: account,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.SynologySession>);

  @override
  _i8.Future<void> logout(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasActiveSession(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveSession, [catalogId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.SynologySession> getOrRefreshSession(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrRefreshSession, [catalogId]),
            returnValue: _i8.Future<_i2.SynologySession>.value(
              _FakeSynologySession_0(
                this,
                Invocation.method(#getOrRefreshSession, [catalogId]),
              ),
            ),
          )
          as _i8.Future<_i2.SynologySession>);

  @override
  _i8.Future<_i3.ListResult> listDirectory(
    String? catalogId,
    String? path, {
    String? sortBy = 'name',
    String? sortDirection = 'asc',
    int? offset = 0,
    int? limit = 0,
    List<String>? extensions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listDirectory,
              [catalogId, path],
              {
                #sortBy: sortBy,
                #sortDirection: sortDirection,
                #offset: offset,
                #limit: limit,
                #extensions: extensions,
              },
            ),
            returnValue: _i8.Future<_i3.ListResult>.value(
              _FakeListResult_1(
                this,
                Invocation.method(
                  #listDirectory,
                  [catalogId, path],
                  {
                    #sortBy: sortBy,
                    #sortDirection: sortDirection,
                    #offset: offset,
                    #limit: limit,
                    #extensions: extensions,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i3.ListResult>);

  @override
  _i8.Future<_i4.SynologyFile> getFileMetadata(
    String? catalogId,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFileMetadata, [catalogId, path]),
            returnValue: _i8.Future<_i4.SynologyFile>.value(
              _FakeSynologyFile_2(
                this,
                Invocation.method(#getFileMetadata, [catalogId, path]),
              ),
            ),
          )
          as _i8.Future<_i4.SynologyFile>);

  @override
  _i8.Future<_i5.File> downloadFile(
    String? catalogId,
    String? remotePath,
    String? localPath, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [catalogId, remotePath, localPath],
              {#onProgress: onProgress},
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #downloadFile,
                  [catalogId, remotePath, localPath],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i8.Future<_i6.SearchResult> search(
    String? catalogId,
    String? keyword, {
    String? fileType,
    String? location = 'mydrive',
    int? offset = 0,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [catalogId, keyword],
              {
                #fileType: fileType,
                #location: location,
                #offset: offset,
                #limit: limit,
              },
            ),
            returnValue: _i8.Future<_i6.SearchResult>.value(
              _FakeSearchResult_4(
                this,
                Invocation.method(
                  #search,
                  [catalogId, keyword],
                  {
                    #fileType: fileType,
                    #location: location,
                    #offset: offset,
                    #limit: limit,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i6.SearchResult>);

  @override
  _i8.Future<_i4.SynologyFile> createFolder(
    String? catalogId,
    String? path, {
    String? conflictAction = 'autorename',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createFolder,
              [catalogId, path],
              {#conflictAction: conflictAction},
            ),
            returnValue: _i8.Future<_i4.SynologyFile>.value(
              _FakeSynologyFile_2(
                this,
                Invocation.method(
                  #createFolder,
                  [catalogId, path],
                  {#conflictAction: conflictAction},
                ),
              ),
            ),
          )
          as _i8.Future<_i4.SynologyFile>);

  @override
  _i8.Future<bool> validateConnection(
    String? serverUrl,
    String? account,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateConnection, [
              serverUrl,
              account,
              password,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> storeCredentials(
    String? catalogId,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeCredentials, [
              catalogId,
              username,
              password,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [SynologySessionStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSynologySessionStorage extends _i1.Mock
    implements _i9.SynologySessionStorage {
  MockSynologySessionStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveSession(
    String? catalogId,
    _i2.SynologySession? session,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [catalogId, session]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.SynologySession?> getSession(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [catalogId]),
            returnValue: _i8.Future<_i2.SynologySession?>.value(),
          )
          as _i8.Future<_i2.SynologySession?>);

  @override
  _i8.Future<void> deleteSession(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasSession(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#hasSession, [catalogId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> saveCredentials(
    String? catalogId,
    String? account,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [catalogId, account, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<(String, String)?> getCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getCredentials, [catalogId]),
            returnValue: _i8.Future<(String, String)?>.value(),
          )
          as _i8.Future<(String, String)?>);

  @override
  _i8.Future<void> deleteCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCredentials, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#hasCredentials, [catalogId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAllForCatalog(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllForCatalog, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
