// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/data/services/nextcloud_news_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:readwhere/domain/entities/catalog.dart' as _i3;
import 'package:readwhere/domain/entities/feed_item.dart' as _i11;
import 'package:readwhere/domain/repositories/catalog_repository.dart' as _i9;
import 'package:readwhere/domain/repositories/feed_item_repository.dart'
    as _i10;
import 'package:readwhere/domain/repositories/nextcloud_news_mapping_repository.dart'
    as _i4;
import 'package:readwhere_nextcloud/src/api/models/nextcloud_news_item.dart'
    as _i7;
import 'package:readwhere_nextcloud/src/api/nextcloud_news_service.dart' as _i2;
import 'package:readwhere_nextcloud/src/storage/credential_storage.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNewsAppAvailabilityResult_0 extends _i1.SmartFake
    implements _i2.NewsAppAvailabilityResult {
  _FakeNewsAppAvailabilityResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNewsFedsResult_1 extends _i1.SmartFake
    implements _i2.NewsFedsResult {
  _FakeNewsFedsResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCatalog_2 extends _i1.SmartFake implements _i3.Catalog {
  _FakeCatalog_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNewsFeedMapping_3 extends _i1.SmartFake
    implements _i4.NewsFeedMapping {
  _FakeNewsFeedMapping_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNewsItemMapping_4 extends _i1.SmartFake
    implements _i4.NewsItemMapping {
  _FakeNewsItemMapping_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NextcloudNewsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNextcloudNewsService extends _i1.Mock
    implements _i2.NextcloudNewsService {
  MockNextcloudNewsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.NewsAppAvailabilityResult> checkAvailability(
    String? serverUrl,
    String? auth,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, [serverUrl, auth]),
            returnValue: _i6.Future<_i2.NewsAppAvailabilityResult>.value(
              _FakeNewsAppAvailabilityResult_0(
                this,
                Invocation.method(#checkAvailability, [serverUrl, auth]),
              ),
            ),
          )
          as _i6.Future<_i2.NewsAppAvailabilityResult>);

  @override
  _i6.Future<_i2.NewsFedsResult> getFeeds(String? serverUrl, String? auth) =>
      (super.noSuchMethod(
            Invocation.method(#getFeeds, [serverUrl, auth]),
            returnValue: _i6.Future<_i2.NewsFedsResult>.value(
              _FakeNewsFedsResult_1(
                this,
                Invocation.method(#getFeeds, [serverUrl, auth]),
              ),
            ),
          )
          as _i6.Future<_i2.NewsFedsResult>);

  @override
  _i6.Future<List<_i7.NextcloudNewsItem>> getItems(
    String? serverUrl,
    String? auth, {
    int? batchSize = 100,
    int? offset,
    int? type = 3,
    int? id,
    bool? getRead = true,
    bool? oldestFirst = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getItems,
              [serverUrl, auth],
              {
                #batchSize: batchSize,
                #offset: offset,
                #type: type,
                #id: id,
                #getRead: getRead,
                #oldestFirst: oldestFirst,
              },
            ),
            returnValue: _i6.Future<List<_i7.NextcloudNewsItem>>.value(
              <_i7.NextcloudNewsItem>[],
            ),
          )
          as _i6.Future<List<_i7.NextcloudNewsItem>>);

  @override
  _i6.Future<List<_i7.NextcloudNewsItem>> getUpdatedItems(
    String? serverUrl,
    String? auth, {
    required int? lastModified,
    int? type = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpdatedItems,
              [serverUrl, auth],
              {#lastModified: lastModified, #type: type},
            ),
            returnValue: _i6.Future<List<_i7.NextcloudNewsItem>>.value(
              <_i7.NextcloudNewsItem>[],
            ),
          )
          as _i6.Future<List<_i7.NextcloudNewsItem>>);

  @override
  _i6.Future<void> markItemRead(String? serverUrl, String? auth, int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#markItemRead, [serverUrl, auth, itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markItemUnread(
    String? serverUrl,
    String? auth,
    int? itemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markItemUnread, [serverUrl, auth, itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markItemsRead(
    String? serverUrl,
    String? auth,
    List<int>? itemIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markItemsRead, [serverUrl, auth, itemIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> starItem(
    String? serverUrl,
    String? auth,
    int? feedId,
    String? guidHash,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#starItem, [serverUrl, auth, feedId, guidHash]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unstarItem(
    String? serverUrl,
    String? auth,
    int? feedId,
    String? guidHash,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unstarItem, [serverUrl, auth, feedId, guidHash]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NextcloudCredentialStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockNextcloudCredentialStorage extends _i1.Mock
    implements _i8.NextcloudCredentialStorage {
  MockNextcloudCredentialStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveAppPassword(String? catalogId, String? appPassword) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppPassword, [catalogId, appPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getAppPassword(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppPassword, [catalogId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> saveAccessToken(String? catalogId, String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [catalogId, accessToken]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessToken(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [catalogId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCredentials, [catalogId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> hasCredentials(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#hasCredentials, [catalogId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getCredential(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getCredential, [catalogId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CatalogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogRepository extends _i1.Mock implements _i9.CatalogRepository {
  MockCatalogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.Catalog>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i3.Catalog>>.value(<_i3.Catalog>[]),
          )
          as _i6.Future<List<_i3.Catalog>>);

  @override
  _i6.Future<_i3.Catalog?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i3.Catalog?>.value(),
          )
          as _i6.Future<_i3.Catalog?>);

  @override
  _i6.Future<_i3.Catalog> insert(_i3.Catalog? catalog) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [catalog]),
            returnValue: _i6.Future<_i3.Catalog>.value(
              _FakeCatalog_2(this, Invocation.method(#insert, [catalog])),
            ),
          )
          as _i6.Future<_i3.Catalog>);

  @override
  _i6.Future<_i3.Catalog> update(_i3.Catalog? catalog) =>
      (super.noSuchMethod(
            Invocation.method(#update, [catalog]),
            returnValue: _i6.Future<_i3.Catalog>.value(
              _FakeCatalog_2(this, Invocation.method(#update, [catalog])),
            ),
          )
          as _i6.Future<_i3.Catalog>);

  @override
  _i6.Future<bool> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> updateLastAccessed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastAccessed, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.Catalog?> findByUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#findByUrl, [url]),
            returnValue: _i6.Future<_i3.Catalog?>.value(),
          )
          as _i6.Future<_i3.Catalog?>);
}

/// A class which mocks [FeedItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedItemRepository extends _i1.Mock
    implements _i10.FeedItemRepository {
  MockFeedItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i11.FeedItem>> getByFeedId(
    String? feedId, {
    bool? unreadOnly = false,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByFeedId,
              [feedId],
              {#unreadOnly: unreadOnly, #limit: limit},
            ),
            returnValue: _i6.Future<List<_i11.FeedItem>>.value(
              <_i11.FeedItem>[],
            ),
          )
          as _i6.Future<List<_i11.FeedItem>>);

  @override
  _i6.Future<_i11.FeedItem?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i11.FeedItem?>.value(),
          )
          as _i6.Future<_i11.FeedItem?>);

  @override
  _i6.Future<void> upsertItems(String? feedId, List<_i11.FeedItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertItems, [feedId, items]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markAsRead(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markAsUnread(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsUnread, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markAllAsRead(String? feedId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [feedId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleStarred(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleStarred, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getUnreadCount(String? feedId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [feedId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<Map<String, int>> getAllUnreadCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUnreadCounts, []),
            returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<void> deleteOldItems(String? feedId, {int? keepCount = 100}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteOldItems,
              [feedId],
              {#keepCount: keepCount},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteByFeedId(String? feedId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByFeedId, [feedId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.FeedItem>> getStarredItems() =>
      (super.noSuchMethod(
            Invocation.method(#getStarredItems, []),
            returnValue: _i6.Future<List<_i11.FeedItem>>.value(
              <_i11.FeedItem>[],
            ),
          )
          as _i6.Future<List<_i11.FeedItem>>);

  @override
  _i6.Future<void> updateFullContent(String? itemId, String? fullContent) =>
      (super.noSuchMethod(
            Invocation.method(#updateFullContent, [itemId, fullContent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NextcloudNewsMappingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNextcloudNewsMappingRepository extends _i1.Mock
    implements _i4.NextcloudNewsMappingRepository {
  MockNextcloudNewsMappingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> getLocalFeedId(String? catalogId, int? ncFeedId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalFeedId, [catalogId, ncFeedId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<int?> getNcFeedId(String? catalogId, String? localFeedId) =>
      (super.noSuchMethod(
            Invocation.method(#getNcFeedId, [catalogId, localFeedId]),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<List<_i4.NewsFeedMapping>> getFeedMappingsForCatalog(
    String? catalogId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedMappingsForCatalog, [catalogId]),
            returnValue: _i6.Future<List<_i4.NewsFeedMapping>>.value(
              <_i4.NewsFeedMapping>[],
            ),
          )
          as _i6.Future<List<_i4.NewsFeedMapping>>);

  @override
  _i6.Future<_i4.NewsFeedMapping?> getFeedMappingByUrl(
    String? catalogId,
    String? feedUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedMappingByUrl, [catalogId, feedUrl]),
            returnValue: _i6.Future<_i4.NewsFeedMapping?>.value(),
          )
          as _i6.Future<_i4.NewsFeedMapping?>);

  @override
  _i6.Future<_i4.NewsFeedMapping> saveFeedMapping({
    required String? catalogId,
    required int? ncFeedId,
    required String? localFeedId,
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFeedMapping, [], {
              #catalogId: catalogId,
              #ncFeedId: ncFeedId,
              #localFeedId: localFeedId,
              #feedUrl: feedUrl,
            }),
            returnValue: _i6.Future<_i4.NewsFeedMapping>.value(
              _FakeNewsFeedMapping_3(
                this,
                Invocation.method(#saveFeedMapping, [], {
                  #catalogId: catalogId,
                  #ncFeedId: ncFeedId,
                  #localFeedId: localFeedId,
                  #feedUrl: feedUrl,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.NewsFeedMapping>);

  @override
  _i6.Future<void> deleteFeedMapping(String? catalogId, int? ncFeedId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFeedMapping, [catalogId, ncFeedId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getLocalItemId(String? catalogId, int? ncItemId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalItemId, [catalogId, ncItemId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<int?> getNcItemId(String? catalogId, String? localItemId) =>
      (super.noSuchMethod(
            Invocation.method(#getNcItemId, [catalogId, localItemId]),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<List<_i4.NewsItemMapping>> getItemMappingsForFeed(
    String? catalogId,
    int? ncFeedId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getItemMappingsForFeed, [catalogId, ncFeedId]),
            returnValue: _i6.Future<List<_i4.NewsItemMapping>>.value(
              <_i4.NewsItemMapping>[],
            ),
          )
          as _i6.Future<List<_i4.NewsItemMapping>>);

  @override
  _i6.Future<Map<int, String>> getLocalItemIds(
    String? catalogId,
    List<int>? ncItemIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalItemIds, [catalogId, ncItemIds]),
            returnValue: _i6.Future<Map<int, String>>.value(<int, String>{}),
          )
          as _i6.Future<Map<int, String>>);

  @override
  _i6.Future<_i4.NewsItemMapping> saveItemMapping({
    required String? catalogId,
    required int? ncItemId,
    required String? localItemId,
    required int? ncFeedId,
    required String? localFeedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveItemMapping, [], {
              #catalogId: catalogId,
              #ncItemId: ncItemId,
              #localItemId: localItemId,
              #ncFeedId: ncFeedId,
              #localFeedId: localFeedId,
            }),
            returnValue: _i6.Future<_i4.NewsItemMapping>.value(
              _FakeNewsItemMapping_4(
                this,
                Invocation.method(#saveItemMapping, [], {
                  #catalogId: catalogId,
                  #ncItemId: ncItemId,
                  #localItemId: localItemId,
                  #ncFeedId: ncFeedId,
                  #localFeedId: localFeedId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.NewsItemMapping>);

  @override
  _i6.Future<void> saveItemMappings(List<_i4.NewsItemMapping>? mappings) =>
      (super.noSuchMethod(
            Invocation.method(#saveItemMappings, [mappings]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteItemMapping(String? catalogId, int? ncItemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItemMapping, [catalogId, ncItemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMappingsForCatalog(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMappingsForCatalog, [catalogId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteItemMappingsForFeed(
    String? catalogId,
    int? ncFeedId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItemMappingsForFeed, [
              catalogId,
              ncFeedId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getFeedMappingCount(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedMappingCount, [catalogId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getItemMappingCount(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemMappingCount, [catalogId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}
