// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/plugins/kavita/kavita_account_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:readwhere_kavita/src/api/kavita_api_client.dart' as _i3;
import 'package:readwhere_kavita/src/models/kavita_progress.dart' as _i6;
import 'package:readwhere_kavita/src/models/kavita_server_info.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKavitaServerInfo_1 extends _i1.SmartFake
    implements _i2.KavitaServerInfo {
  _FakeKavitaServerInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KavitaApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockKavitaApiClient extends _i1.Mock implements _i3.KavitaApiClient {
  MockKavitaApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.KavitaServerInfo> authenticate(
    String? serverUrl,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [serverUrl, apiKey]),
            returnValue: _i5.Future<_i2.KavitaServerInfo>.value(
              _FakeKavitaServerInfo_1(
                this,
                Invocation.method(#authenticate, [serverUrl, apiKey]),
              ),
            ),
          )
          as _i5.Future<_i2.KavitaServerInfo>);

  @override
  _i5.Future<_i6.KavitaProgress?> getProgress(
    String? serverUrl,
    String? apiKey,
    int? chapterId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgress, [serverUrl, apiKey, chapterId]),
            returnValue: _i5.Future<_i6.KavitaProgress?>.value(),
          )
          as _i5.Future<_i6.KavitaProgress?>);

  @override
  _i5.Future<void> updateProgress(
    String? serverUrl,
    String? apiKey,
    _i6.KavitaProgress? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [serverUrl, apiKey, progress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markChapterRead(
    String? serverUrl,
    String? apiKey, {
    required int? seriesId,
    required int? volumeId,
    required int? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markChapterRead,
              [serverUrl, apiKey],
              {#seriesId: seriesId, #volumeId: volumeId, #chapterId: chapterId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
