// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/plugins/kavita/kavita_account_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readwhere/data/services/kavita_api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKavitaServerInfo_0 extends _i1.SmartFake
    implements _i2.KavitaServerInfo {
  _FakeKavitaServerInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KavitaApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKavitaApiService extends _i1.Mock implements _i2.KavitaApiService {
  MockKavitaApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.KavitaServerInfo> authenticate(
    String? serverUrl,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [serverUrl, apiKey]),
            returnValue: _i3.Future<_i2.KavitaServerInfo>.value(
              _FakeKavitaServerInfo_0(
                this,
                Invocation.method(#authenticate, [serverUrl, apiKey]),
              ),
            ),
          )
          as _i3.Future<_i2.KavitaServerInfo>);

  @override
  _i3.Future<_i2.KavitaProgress?> getProgress(
    String? serverUrl,
    String? apiKey,
    int? chapterId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgress, [serverUrl, apiKey, chapterId]),
            returnValue: _i3.Future<_i2.KavitaProgress?>.value(),
          )
          as _i3.Future<_i2.KavitaProgress?>);

  @override
  _i3.Future<void> updateProgress(
    String? serverUrl,
    String? apiKey,
    _i2.KavitaProgress? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [serverUrl, apiKey, progress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markChapterRead(
    String? serverUrl,
    String? apiKey, {
    required int? seriesId,
    required int? volumeId,
    required int? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markChapterRead,
              [serverUrl, apiKey],
              {#seriesId: seriesId, #volumeId: volumeId, #chapterId: chapterId},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
