// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere/test/plugins/kavita/kavita_catalog_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:readwhere/data/services/opds_cache_service.dart' as _i12;
import 'package:readwhere/domain/repositories/opds_cache_repository.dart'
    as _i5;
import 'package:readwhere_kavita/src/api/kavita_api_client.dart' as _i6;
import 'package:readwhere_kavita/src/models/kavita_progress.dart' as _i9;
import 'package:readwhere_kavita/src/models/kavita_server_info.dart' as _i2;
import 'package:readwhere_opds/readwhere_opds.dart' as _i4;
import 'package:readwhere_opds/src/entities/opds_feed.dart' as _i3;
import 'package:readwhere_opds/src/entities/opds_link.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKavitaServerInfo_1 extends _i1.SmartFake
    implements _i2.KavitaServerInfo {
  _FakeKavitaServerInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOpdsFeed_2 extends _i1.SmartFake implements _i3.OpdsFeed {
  _FakeOpdsFeed_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCachedFeedResult_3 extends _i1.SmartFake
    implements _i4.CachedFeedResult {
  _FakeCachedFeedResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheStats_4 extends _i1.SmartFake implements _i5.CacheStats {
  _FakeCacheStats_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KavitaApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockKavitaApiClient extends _i1.Mock implements _i6.KavitaApiClient {
  MockKavitaApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  _i8.Future<_i2.KavitaServerInfo> authenticate(
    String? serverUrl,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [serverUrl, apiKey]),
            returnValue: _i8.Future<_i2.KavitaServerInfo>.value(
              _FakeKavitaServerInfo_1(
                this,
                Invocation.method(#authenticate, [serverUrl, apiKey]),
              ),
            ),
          )
          as _i8.Future<_i2.KavitaServerInfo>);

  @override
  _i8.Future<_i9.KavitaProgress?> getProgress(
    String? serverUrl,
    String? apiKey,
    int? chapterId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgress, [serverUrl, apiKey, chapterId]),
            returnValue: _i8.Future<_i9.KavitaProgress?>.value(),
          )
          as _i8.Future<_i9.KavitaProgress?>);

  @override
  _i8.Future<void> updateProgress(
    String? serverUrl,
    String? apiKey,
    _i9.KavitaProgress? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [serverUrl, apiKey, progress]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> markChapterRead(
    String? serverUrl,
    String? apiKey, {
    required int? seriesId,
    required int? volumeId,
    required int? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markChapterRead,
              [serverUrl, apiKey],
              {#seriesId: seriesId, #volumeId: volumeId, #chapterId: chapterId},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OpdsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpdsClient extends _i1.Mock implements _i4.OpdsClient {
  MockOpdsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  _i8.Future<_i3.OpdsFeed> validateCatalog(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#validateCatalog, [url]),
            returnValue: _i8.Future<_i3.OpdsFeed>.value(
              _FakeOpdsFeed_2(this, Invocation.method(#validateCatalog, [url])),
            ),
          )
          as _i8.Future<_i3.OpdsFeed>);

  @override
  _i8.Future<_i3.OpdsFeed> fetchFeed(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFeed, [url]),
            returnValue: _i8.Future<_i3.OpdsFeed>.value(
              _FakeOpdsFeed_2(this, Invocation.method(#fetchFeed, [url])),
            ),
          )
          as _i8.Future<_i3.OpdsFeed>);

  @override
  _i8.Future<_i3.OpdsFeed> fetchFeedPage(String? url, {int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFeedPage, [url], {#page: page}),
            returnValue: _i8.Future<_i3.OpdsFeed>.value(
              _FakeOpdsFeed_2(
                this,
                Invocation.method(#fetchFeedPage, [url], {#page: page}),
              ),
            ),
          )
          as _i8.Future<_i3.OpdsFeed>);

  @override
  _i8.Future<_i3.OpdsFeed> search(_i3.OpdsFeed? rootFeed, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [rootFeed, query]),
            returnValue: _i8.Future<_i3.OpdsFeed>.value(
              _FakeOpdsFeed_2(
                this,
                Invocation.method(#search, [rootFeed, query]),
              ),
            ),
          )
          as _i8.Future<_i3.OpdsFeed>);

  @override
  _i8.Future<_i3.OpdsFeed> searchWithUrl(
    String? catalogUrl,
    String? searchPath,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchWithUrl, [catalogUrl, searchPath, query]),
            returnValue: _i8.Future<_i3.OpdsFeed>.value(
              _FakeOpdsFeed_2(
                this,
                Invocation.method(#searchWithUrl, [
                  catalogUrl,
                  searchPath,
                  query,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.OpdsFeed>);

  @override
  _i8.Future<String> downloadBook(
    _i10.OpdsLink? link,
    _i11.Directory? downloadDir, {
    String? filename,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadBook,
              [link, downloadDir],
              {#filename: filename, #onProgress: onProgress},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #downloadBook,
                  [link, downloadDir],
                  {#filename: filename, #onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String resolveCoverUrl(String? baseUrl, String? coverPath) =>
      (super.noSuchMethod(
            Invocation.method(#resolveCoverUrl, [baseUrl, coverPath]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#resolveCoverUrl, [baseUrl, coverPath]),
            ),
          )
          as String);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OpdsCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpdsCacheService extends _i1.Mock implements _i12.OpdsCacheService {
  MockOpdsCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.CachedFeedResult> fetchFeed({
    required String? catalogId,
    required String? url,
    required _i4.FetchStrategy? strategy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFeed, [], {
              #catalogId: catalogId,
              #url: url,
              #strategy: strategy,
            }),
            returnValue: _i8.Future<_i4.CachedFeedResult>.value(
              _FakeCachedFeedResult_3(
                this,
                Invocation.method(#fetchFeed, [], {
                  #catalogId: catalogId,
                  #url: url,
                  #strategy: strategy,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.CachedFeedResult>);

  @override
  _i8.Future<void> prefetchFeed(String? catalogId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchFeed, [catalogId, url]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.CachedFeedResult> refreshFeed(
    String? catalogId,
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshFeed, [catalogId, url]),
            returnValue: _i8.Future<_i4.CachedFeedResult>.value(
              _FakeCachedFeedResult_3(
                this,
                Invocation.method(#refreshFeed, [catalogId, url]),
              ),
            ),
          )
          as _i8.Future<_i4.CachedFeedResult>);

  @override
  _i8.Future<bool> hasFreshCache(String? catalogId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#hasFreshCache, [catalogId, url]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.CacheStats> getCacheStats(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, [catalogId]),
            returnValue: _i8.Future<_i5.CacheStats>.value(
              _FakeCacheStats_4(
                this,
                Invocation.method(#getCacheStats, [catalogId]),
              ),
            ),
          )
          as _i8.Future<_i5.CacheStats>);

  @override
  _i8.Future<_i5.CacheStats> getAllCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCacheStats, []),
            returnValue: _i8.Future<_i5.CacheStats>.value(
              _FakeCacheStats_4(this, Invocation.method(#getAllCacheStats, [])),
            ),
          )
          as _i8.Future<_i5.CacheStats>);

  @override
  _i8.Future<int> cleanupExpiredCache() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredCache, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> clearCache(String? catalogId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [catalogId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCaches() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCaches, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
