// Mocks generated by Mockito 5.4.6 from annotations
// in readwhere_nextcloud/test/provider/nextcloud_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readwhere_nextcloud/src/api/models/server_info.dart' as _i5;
import 'package:readwhere_nextcloud/src/api/nextcloud_client.dart' as _i7;
import 'package:readwhere_nextcloud/src/api/ocs_api_service.dart' as _i2;
import 'package:readwhere_nextcloud/src/auth/models/login_flow_init.dart'
    as _i6;
import 'package:readwhere_nextcloud/src/auth/models/login_flow_result.dart'
    as _i9;
import 'package:readwhere_nextcloud/src/storage/credential_storage.dart' as _i4;
import 'package:readwhere_nextcloud/src/webdav/nextcloud_file.dart' as _i10;
import 'package:readwhere_nextcloud/src/webdav/nextcloud_webdav.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOcsApiService_0 extends _i1.SmartFake implements _i2.OcsApiService {
  _FakeOcsApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNextcloudWebDav_1 extends _i1.SmartFake
    implements _i3.NextcloudWebDav {
  _FakeNextcloudWebDav_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNextcloudCredentialStorage_2 extends _i1.SmartFake
    implements _i4.NextcloudCredentialStorage {
  _FakeNextcloudCredentialStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNextcloudServerInfo_3 extends _i1.SmartFake
    implements _i5.NextcloudServerInfo {
  _FakeNextcloudServerInfo_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginFlowInit_4 extends _i1.SmartFake implements _i6.LoginFlowInit {
  _FakeLoginFlowInit_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NextcloudClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNextcloudClient extends _i1.Mock implements _i7.NextcloudClient {
  MockNextcloudClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OcsApiService get api => (super.noSuchMethod(
        Invocation.getter(#api),
        returnValue: _FakeOcsApiService_0(
          this,
          Invocation.getter(#api),
        ),
      ) as _i2.OcsApiService);

  @override
  _i3.NextcloudWebDav get webdav => (super.noSuchMethod(
        Invocation.getter(#webdav),
        returnValue: _FakeNextcloudWebDav_1(
          this,
          Invocation.getter(#webdav),
        ),
      ) as _i3.NextcloudWebDav);

  @override
  _i4.NextcloudCredentialStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeNextcloudCredentialStorage_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i4.NextcloudCredentialStorage);

  @override
  _i8.Future<_i5.NextcloudServerInfo> validateAppPassword(
    String? serverUrl,
    String? username,
    String? appPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAppPassword,
          [
            serverUrl,
            username,
            appPassword,
          ],
        ),
        returnValue: _i8.Future<_i5.NextcloudServerInfo>.value(
            _FakeNextcloudServerInfo_3(
          this,
          Invocation.method(
            #validateAppPassword,
            [
              serverUrl,
              username,
              appPassword,
            ],
          ),
        )),
      ) as _i8.Future<_i5.NextcloudServerInfo>);

  @override
  _i8.Future<_i6.LoginFlowInit> initiateOAuthFlow(String? serverUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateOAuthFlow,
          [serverUrl],
        ),
        returnValue: _i8.Future<_i6.LoginFlowInit>.value(_FakeLoginFlowInit_4(
          this,
          Invocation.method(
            #initiateOAuthFlow,
            [serverUrl],
          ),
        )),
      ) as _i8.Future<_i6.LoginFlowInit>);

  @override
  _i8.Future<_i9.LoginFlowResult?> pollOAuthFlow(
    String? pollEndpoint,
    String? pollToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pollOAuthFlow,
          [
            pollEndpoint,
            pollToken,
          ],
        ),
        returnValue: _i8.Future<_i9.LoginFlowResult?>.value(),
      ) as _i8.Future<_i9.LoginFlowResult?>);

  @override
  _i8.Future<bool> isNextcloudServer(String? serverUrl) => (super.noSuchMethod(
        Invocation.method(
          #isNextcloudServer,
          [serverUrl],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> saveCredentials(
    String? catalogId,
    String? appPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCredentials,
          [
            catalogId,
            appPassword,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCredentials(String? catalogId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCredentials,
          [catalogId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> hasCredentials(String? catalogId) => (super.noSuchMethod(
        Invocation.method(
          #hasCredentials,
          [catalogId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i10.NextcloudFile>> listDirectory({
    required String? serverUrl,
    required String? userId,
    required String? catalogId,
    required String? username,
    required String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listDirectory,
          [],
          {
            #serverUrl: serverUrl,
            #userId: userId,
            #catalogId: catalogId,
            #username: username,
            #path: path,
          },
        ),
        returnValue:
            _i8.Future<List<_i10.NextcloudFile>>.value(<_i10.NextcloudFile>[]),
      ) as _i8.Future<List<_i10.NextcloudFile>>);

  @override
  _i8.Future<List<_i10.NextcloudFile>> listDirectoryWithCredentials({
    required String? serverUrl,
    required String? userId,
    required String? username,
    required String? password,
    required String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listDirectoryWithCredentials,
          [],
          {
            #serverUrl: serverUrl,
            #userId: userId,
            #username: username,
            #password: password,
            #path: path,
          },
        ),
        returnValue:
            _i8.Future<List<_i10.NextcloudFile>>.value(<_i10.NextcloudFile>[]),
      ) as _i8.Future<List<_i10.NextcloudFile>>);

  @override
  _i8.Future<void> downloadFile({
    required String? serverUrl,
    required String? userId,
    required String? catalogId,
    required String? username,
    required String? remotePath,
    required String? localPath,
    void Function(
      int,
      int,
    )? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [],
          {
            #serverUrl: serverUrl,
            #userId: userId,
            #catalogId: catalogId,
            #username: username,
            #remotePath: remotePath,
            #localPath: localPath,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
